package com.shirly.data.mapper;

import com.shirly.data.base.Menutype;
import com.shirly.data.base.MenutypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenutypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    long countByExample(MenutypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int deleteByExample(MenutypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int insert(Menutype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int insertSelective(Menutype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    List<Menutype> selectByExample(MenutypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    Menutype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") Menutype record, @Param("example") MenutypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int updateByExample(@Param("record") Menutype record, @Param("example") MenutypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int updateByPrimaryKeySelective(Menutype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menutype
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    int updateByPrimaryKey(Menutype record);
}