package com.shirly.data.base;

import java.util.Date;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menuId
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private Integer menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.mName
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.mTid
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private Integer mtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.price
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.offerPrice
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private Float offerprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.createTime
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.updateTime
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuId
     *
     * @return the value of menu.menuId
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuId
     *
     * @param menuid the value for menu.menuId
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.mName
     *
     * @return the value of menu.mName
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.mName
     *
     * @param mname the value for menu.mName
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.mTid
     *
     * @return the value of menu.mTid
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public Integer getMtid() {
        return mtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.mTid
     *
     * @param mtid the value for menu.mTid
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setMtid(Integer mtid) {
        this.mtid = mtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.price
     *
     * @return the value of menu.price
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.price
     *
     * @param price the value for menu.price
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.offerPrice
     *
     * @return the value of menu.offerPrice
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public Float getOfferprice() {
        return offerprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.offerPrice
     *
     * @param offerprice the value for menu.offerPrice
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setOfferprice(Float offerprice) {
        this.offerprice = offerprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.createTime
     *
     * @return the value of menu.createTime
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.createTime
     *
     * @param createtime the value for menu.createTime
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.updateTime
     *
     * @return the value of menu.updateTime
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.updateTime
     *
     * @param updatetime the value for menu.updateTime
     *
     * @mbg.generated Fri Aug 09 16:30:07 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}